### ISSUE TITLE
Flake8 3.0 is incompatible with teamcity-messages

### ISSUE THREAD

**Issue by cmaloney** [JetBrains/teamcity-messages#105]
The plugin API seems to have changed quite a bit in 3.0

One example of a build failure resulting for this: https://teamcity.mesosphere.io/viewLog.html?buildId=343692&buildTypeId=DcosIo_Dcos_CodeQuality&tab=buildLog#_focus=503

Temporary workaround is to pin flake8 to 2.6.2

Sampe backtrace:
```
flake8.plugins.manager    MainProcess    104 INFO     Loading entry-points for "flake8.extension".
flake8.plugins.manager    MainProcess    152 INFO     Loading entry-points for "flake8.listen".
flake8.plugins.manager    MainProcess    152 INFO     Loading entry-points for "flake8.report".
flake8.plugins.manager    MainProcess    152 INFO     Loading plugin "pycodestyle.python_3000_has_key" from entry-point.
flake8.plugins.manager    MainProcess    158 INFO     Loading plugin "pycodestyle.trailing_blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    158 INFO     Loading plugin "pycodestyle.break_around_binary_operator" from entry-point.
flake8.plugins.manager    MainProcess    158 INFO     Loading plugin "pycodestyle.explicit_line_join" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.module_imports_on_top_of_file" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.extraneous_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.imports_on_separate_lines" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.indentation" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.whitespace_before_parameters" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.python_3000_not_equal" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.python_3000_backticks" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.whitespace_around_named_parameter_equals" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "pycodestyle.python_3000_raise_comma" from entry-point.
flake8.plugins.manager    MainProcess    159 INFO     Loading plugin "F" from entry-point.
flake8.plugins.manager    MainProcess    173 INFO     Loading plugin "pycodestyle.missing_whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    173 INFO     Loading plugin "pycodestyle.whitespace_around_keywords" from entry-point.
flake8.plugins.manager    MainProcess    173 INFO     Loading plugin "pycodestyle.comparison_negative" from entry-point.
flake8.plugins.manager    MainProcess    173 INFO     Loading plugin "pycodestyle.compound_statements" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.continued_indentation" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.maximum_line_length" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.whitespace_before_comment" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.comparison_type" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.missing_whitespace_after_import_keyword" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.tabs_or_spaces" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.missing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.trailing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.whitespace_around_comma" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.comparison_to_singleton" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "pycodestyle.tabs_obsolete" from entry-point.
flake8.plugins.manager    MainProcess    174 INFO     Loading plugin "P999" from entry-point.
flake8.plugins.manager    MainProcess    175 INFO     Loading plugin "C90" from entry-point.
flake8.plugins.manager    MainProcess    175 INFO     Loading plugin "pylint" from entry-point.
flake8.plugins.manager    MainProcess    176 INFO     Loading plugin "default" from entry-point.
Traceback (most recent call last):
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/plugins/manager.py", line 184, in provide_options
    parse_options(optmanager, options, extra_args)
TypeError: parse_options() takes 1 positional argument but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".tox/py34-syntax/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/main/application.py", line 299, in run
    self._run(argv)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/main/application.py", line 285, in _run
    self.initialize(argv)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/main/application.py", line 277, in initialize
    self.parse_configuration_and_cli(argv)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/main/application.py", line 172, in parse_configuration_and_cli
    self.args)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/plugins/manager.py", line 395, in provide_options
    list(self.manager.map(call_provide_options))
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/plugins/manager.py", line 261, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/plugins/manager.py", line 357, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/flake8/plugins/manager.py", line 186, in provide_options
    parse_options(options)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/teamcity/flake8_plugin.py", line 33, in parse_options
    options.report = TeamcityReport(options)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/pycodestyle.py", line 1756, in __init__
    super(StandardReport, self).__init__(options)
  File "/teamcity/work/19ad0dff41587ee6/.tox/py34-syntax/lib/python3.4/site-packages/pycodestyle.py", line 1662, in __init__
    self._benchmark_keys = options.benchmark_keys
AttributeError: 'Values' object has no attribute 'benchmark_keys'
```

**Comment by cmaloney** [comment]
Thanks @shalupov, @msabramo, @sigmavirus24, seems to be working well!


The PR in my project for going back: https://github.com/dcos/dcos/pull/480
