### ISSUE TITLE
Unittest on Py2: test borken with chars wider than 7 bits (not ascii)

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/teamcity-messages#138]
```
# -*- coding: utf-8 -*-
import unittest


class TestCase(unittest.TestCase):
    @unittest.skip(u"Здесь ошибка")
    def test(self):
        self.assertEqual(2+2, 5)


import unittest
from teamcity import is_running_under_teamcity
from teamcity.unittestpy import TeamcityTestRunner


runner = TeamcityTestRunner()
unittest.main(testRunner=runner)
```

And result
```
C:\temp\untitled13>C:\Python27\python.exe test_test.py
##teamcity[testCount timestamp='2017-05-10T22:06:18.986' count='1']
##teamcity[testStarted timestamp='2017-05-10T22:06:18.987' captureStandardOutput='true' flowId='__main__.TestCase.test' name='__main__.TestCase.test']
##teamcity[testFinished timestamp='2017-05-10T22:06:18.987' duration='0' flowId='__main__.TestCase.test' name='__main__.TestCase.test']
Traceback (most recent call last):
  File "test_test.py", line 17, in <module>
    unittest.main(testRunner=runner)
  File "C:\Python27\lib\unittest\main.py", line 95, in __init__
    self.runTests()
  File "C:\Python27\lib\unittest\main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "C:\temp\untitled13\teamcity\unittestpy.py", line 244, in run
    return super(TeamcityTestRunner, self).run(test)
  File "C:\Python27\lib\unittest\runner.py", line 151, in run
    test(result)
  File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "C:\Python27\lib\unittest\suite.py", line 108, in run
    test(result)
  File "C:\Python27\lib\unittest\suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "C:\Python27\lib\unittest\suite.py", line 108, in run
    test(result)
  File "C:\Python27\lib\unittest\case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "C:\Python27\lib\unittest\case.py", line 313, in run
    self._addSkip(result, skip_why)
  File "C:\Python27\lib\unittest\case.py", line 289, in _addSkip
    addSkip(self, reason)
  File "C:\temp\untitled13\teamcity\unittestpy.py", line 72, in addSkip
    reason_str = ": " + str(reason)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```

**Comment by throwable-one** [comment]
https://youtrack.jetbrains.com/issue/PY-23738
