### ISSUE TITLE
Error ignored in nosetest

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/teamcity-messages#144]
https://youtrack.jetbrains.com/issue/PY-15185

```
virt) C:\temp\nose-failure-catch>c:\temp\virt\Scripts\nosetests.exe test_my_module.py
##teamcity[testStarted timestamp='2017-07-19T16:49:29.294' captureStandardOutput='false' flowId='test_my_module.FailingTestCase.test_fail_due_to_methodcalling' name='test_my_module.FailingTestCase.test_fail_due_to_me
thodcalling']
##teamcity[testFinished timestamp='2017-07-19T16:49:29.294' duration='0' flowId='test_my_module.FailingTestCase.test_fail_due_to_methodcalling' name='test_my_module.FailingTestCase.test_fail_due_to_methodcalling']
F
======================================================================
FAIL: test_fail_due_to_methodcalling (test_my_module.FailingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\temp\virt\lib\site-packages\flexmock.py", line 1286, in stopTest
    flexmock_teardown()
  File "c:\temp\virt\lib\site-packages\flexmock.py", line 1180, in flexmock_teardown
    _getattr(expectation, 'verify')()
  File "c:\temp\virt\lib\site-packages\flexmock.py", line 620, in verify
    (_format_args(self.name, self.args), message, self.times_called))
  File "c:\temp\virt\lib\site-packages\flexmock.py", line 349, in __raise
    raise exception(message)
flexmock.MethodCallError: _submethod() expected to be called exactly 3 times, called 2 times

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
```

There is ``testFinished `` but nothing about failure

**Comment by shalupov** [comment]
flexmock incorrectly monkey-patches us, there is even an issue about it: https://github.com/bkabrda/flexmock/issues/19

note that unittest and nose support in pycharm/teamcity-messages are totally different
