### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 270-272: ordinal not in range(128)

### ISSUE THREAD

**Issue by bazuka-joe** [JetBrains/teamcity-messages#151]
Hi!

in my test there are Russian letters and tests in teamcity failed:

```
2017-09-04 06:38:11,075:ERROR:root:Uncaught exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/teamcity/unittestpy.py", line 171, in <module>
    main(module=None, testRunner=TeamcityTestRunner())
  File "/usr/local/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/local/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/local/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/local/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.6/unittest/case.py", line 613, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/usr/local/lib/python3.6/unittest/case.py", line 538, in _feedErrorsToResult
    result.addSubTest(test.test_case, test, exc_info)
  File "/usr/local/lib/python3.6/site-packages/teamcity/unittestpy.py", line 109, in addSubTest
    self.messages.testStdOut(test_id, out="%s: ok\n" % self.get_test_id(subtest), flowId=test_id)
  File "/usr/local/lib/python3.6/site-packages/teamcity/messages.py", line 131, in testStdOut
    self.message('testStdOut', name=testName, out=out, flowId=flowId)
  File "/usr/local/lib/python3.6/site-packages/teamcity/messages.py", line 68, in message
    self.output.write(self.encode(message))
  File "/usr/local/lib/python3.6/site-packages/teamcity/messages.py", line 39, in encode
    value = value.encode(self.encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 270-272: ordinal not in range(128)
```

```
pip3.6 show teamcity-messages
Name: teamcity-messages
Version: 1.21
Summary: Send test results to TeamCity continuous integration server from unittest, nose, py.test, twisted trial (Python 2.4+)
Home-page: https://github.com/JetBrains/teamcity-messages
Author: JetBrains
Author-email: teamcity-feedback@jetbrains.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires:
```

**Comment by bazuka-joe** [comment]
update

the test case that crashes:

```
    def test_decode_internationalized_domain_name(self):
        for url, expected in [
            (u'https://xn--b1aew.xn--p1ai/', u'мвд.рф'),
            (u'http://xn--knigsgchen-b4a3dun.de/', u'königsgäßchen.de'),
            (u'http://f:42@xn--b1aew.xn--p1ai/', u'мвд.рф'),
            (u'http://.../hello', u'...'),
            (u'http://great_britain.ru', u'great_britain.ru'),
        ]:
            with self.subTest(url=url, decoded=expected):
                self.assertEqual(expected, Url(url, decode_idn=True).host)
```

**Comment by throwable-one** [comment]
Hello.
Have you tried to set ``PYTHONIOENCODING=UTF-8`` env. variable for agent or configuration?

**Comment by grmmvv** [comment]
Hi, there I have similar issue with teamcity-messages and pytest-xdist. Here is case that cause crash:
`
def test_sample():
    assert 0, 'Кириллица'
`
If i start this code without using pytest-xdist, then crash in not happened, but if i use `pytest -n 3`, then internal crash happens.

`PYTHONIOENCODING=UTF-8` and `LC_CTYPE=ru_RU.UTF-8` are setted up.

**Comment by TimurNurlygayanov** [comment]
I've found the workaround!!!

Just add the following line into the beginning of all files with tests:

# -*- coding: utf-8 -*-

**Comment by TimurNurlygayanov** [comment]
how it also can be fixed:

in file env/lib/python3.4/site-packages/teamcity/messages.py
set utf8 by default:

```
class TeamcityServiceMessages(object):
    def __init__(self, output=sys.stdout, now=datetime.datetime.now, encoding='utf-8'):
```

**Comment by kamichal** [comment]
It's going to be 5 years soon, but nobody fixed it yet?

**Comment by kamichal** [comment]
Python 3.11, and it still fails.

Reproduction:
```py
def test_thing():
    raise ValueError("Älä koske")  # any unicode character crashes this package
```

Result:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/_pytest/main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/_pytest/runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/_pytest/runner.py", line 131, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/_pytest/runner.py", line 224, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/xxxx/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/share/pycharm/plugins/python-ce/helpers/pycharm/teamcity/pytest_plugin.py", line 310, in pytest_runtest_logreport
INTERNALERROR>     self.report_test_failure(test_id, report)
INTERNALERROR>   File "/usr/share/pycharm/plugins/python-ce/helpers/pycharm/teamcity/pytest_plugin.py", line 265, in report_test_failure
INTERNALERROR>     self.teamcity.testFailed(test_id, message, str(report.longrepr), flowId=test_id)
INTERNALERROR>   File "/usr/share/pycharm/plugins/python-ce/helpers/pycharm/_jb_runner_tools.py", line 188, in testFailed
INTERNALERROR>     _old_service_messages.testFailed(self, testName, message, details, comparison_failure=comparison_failure)
INTERNALERROR>   File "/usr/share/pycharm/plugins/python-ce/helpers/pycharm/teamcity/messages.py", line 174, in testFailed
INTERNALERROR>     self.message('testFailed', name=testName, message=message, details=details, flowId=flowId)
INTERNALERROR>   File "/usr/share/pycharm/plugins/python-ce/helpers/pycharm/_jb_runner_tools.py", line 117, in message
INTERNALERROR>     _old_service_messages.message(self, messageName, **properties)
INTERNALERROR>   File "/usr/share/pycharm/plugins/python-ce/helpers/pycharm/teamcity/messages.py", line 101, in message
INTERNALERROR>     retry_on_EAGAIN(self.output.write)(self.encode(message))
INTERNALERROR>                                        ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/share/pycharm/plugins/python-ce/helpers/pycharm/teamcity/messages.py", line 68, in encode
INTERNALERROR>     value = value.encode(self.encoding)
INTERNALERROR>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> UnicodeEncodeError: 'ascii' codec can't encode character '\xc4' in position 122: ordinal not in range(128)
```
Runing the pytest in console has no problems. Reports an exception as expected.
