### ISSUE TITLE
Incorrect Flask test leads to testFailed reported without testStarted

### ISSUE THREAD

**Issue by throwable-one** [JetBrains/teamcity-messages#153]
https://youtrack.jetbrains.com/issue/PY-26026

**Comment by shalupov** [comment]
given the following test file:
```
from flask_testing import TestCase
class TestFoo(TestCase):
    def test_add(self):
        self.assertEqual(1 + 2, 3)
````
running tests in PyCharm or from command line yield the following exception:
```
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/home/shalupov/.local/lib/python2.7/site-packages/flask_testing/utils.py", line 131, in __call__
    self._pre_setup()
  File "/home/shalupov/.local/lib/python2.7/site-packages/flask_testing/utils.py", line 137, in _pre_setup
    self.app = self.create_app()
  File "/home/shalupov/.local/lib/python2.7/site-packages/flask_testing/utils.py", line 122, in create_app
    raise NotImplementedError
```
which is totally fine.

but teamcity-messages reports testFailed without testStarted message:
```
[testCount count='1']
[testFailed message='Error' name='test_foo.TestFoo.test_add' details='Traceback (most recent call last):|n  _TRACE_BACK_HERE_NotImplementedError|nNotImplementedError|n']
[testFinished name='test_foo.TestFoo.test_add']
```
