### ISSUE TITLE
Statistics report failure w/ `coverage` == 5.1

### ISSUE THREAD

**Issue by zaufi** [JetBrains/teamcity-messages#234]
```
Coverage statistics reporting failed
Traceback (most recent call last):
  File "/work/.venv/lib/python3.8/site-packages/teamcity/pytest_plugin.py", line 371, in pytest_terminal_summary
    self._report_coverage()
  File "/work/.venv/lib/python3.8/site-packages/teamcity/pytest_plugin.py", line 378, in _report_coverage
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter' from 'coverage.report' (/work/.venv/lib/python3.8/site-packages/coverage/report.py)
```

**Comment by wlievens** [comment]
This issue is al but making this plugin useless...

**Comment by madlexa** [comment]
It is working starting from version 1.28.
