### ISSUE TITLE
Flake8 5.0.0: NotImplementedError: what plugin type?

### ISSUE THREAD

**Issue by yamnikov-oleg** [JetBrains/teamcity-messages#264]
flake8 5.0.0 breaks teamcity-messages:

```
Traceback (most recent call last):
  File "/home/ubuntu/BuildAgent/work/4dc31e662c1dfae/.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/BuildAgent/work/4dc31e662c1dfae/.venv/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/ubuntu/BuildAgent/work/4dc31e662c1dfae/.venv/lib/python3.8/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/home/ubuntu/BuildAgent/work/4dc31e662c1dfae/.venv/lib/python3.8/site-packages/flake8/main/application.py", line 324, in _run
    self.initialize(argv)
  File "/home/ubuntu/BuildAgent/work/4dc31e662c1dfae/.venv/lib/python3.8/site-packages/flake8/main/application.py", line 302, in initialize
    self.find_plugins(
  File "/home/ubuntu/BuildAgent/work/4dc31e662c1dfae/.venv/lib/python3.8/site-packages/flake8/main/application.py", line 128, in find_plugins
    self.plugins = finder.load_plugins(raw, opts)
  File "/home/ubuntu/BuildAgent/work/4dc31e662c1dfae/.venv/lib/python3.8/site-packages/flake8/plugins/finder.py", line 370, in load_plugins
    return _classify_plugins(_import_plugins(plugins, opts), opts)
  File "/home/ubuntu/BuildAgent/work/4dc31e662c1dfae/.venv/lib/python3.8/site-packages/flake8/plugins/finder.py", line 340, in _classify_plugins
    raise NotImplementedError(f"what plugin type? {loaded}")
NotImplementedError: what plugin type? LoadedPlugin(plugin=Plugin(package='teamcity-messages', version='1.31', entry_point=EntryPoint(name='teamcity-messages', value='teamcity.flake8_plugin:TeamcityReport', group='flake8.extension')), obj=<class 'teamcity.flake8_v3_plugin.TeamcityReport'>, parameters={'options': True})
```

The traceback is from flake8 5.0.1, but I suppose the breaking update is 5.0.0.

**Comment by ikrivosheev** [comment]
Hello! When can we expect publication on pypi?)

**Comment by MT-Cash** [comment]
Is there even a fix?

**Comment by lego963** [comment]
> Is there even a fix?

yes, they've released 1.32, but didn't publish on pypi :D

**Comment by MT-Cash** [comment]
@mikekidya Could you push `teamcity-messages==1.32` to PyPI? 

See:

* https://github.com/JetBrains/teamcity-messages/releases/tag/v1.32
* https://pypi.org/project/teamcity-messages/ only 1.31

**Comment by mikekidya** [comment]
Hi! Sorry for the delay, the release is here 
https://pypi.org/project/teamcity-messages/1.32/

Please let me know if anything is not working for you

**Comment by g-rutter** [comment]
@mikekidya  Could we please get the conda forge package released? https://github.com/conda-forge/teamcity-messages-feedstock/pull/4
