### ISSUE TITLE
The sdist is missing tests

### ISSUE THREAD

**Issue by mtelka** [JetBrains/teamcity-messages#271]
The sdist at PyPI is missing support for tests.  Both the `tests` directory and the `tox.ini` file are missing.  Please add them to the sdist to make the downstream testing possible.  Thank you.

**Comment by mtelka** [comment]
Unfortunately, the current `tox.ini` is unusable because the `test` command for `setup.py` is no longer supported and testing fails with:
```
py39: remove tox env folder /data/builds/oi-userland/components/python/teamcity-messages/build/amd64-3.9/.tox/py39
py39: commands[0]> python setup.py test
/data/builds/oi-userland/components/python/teamcity-messages/build/amd64-3.9/setup.py:7: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
!!

        ********************************************************************************
        Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.
        ********************************************************************************

!!
  from setuptools.command.test import test as TestCommand
/usr/lib/python3.9/vendor-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running test
Traceback (most recent call last):
  File "/data/builds/oi-userland/components/python/teamcity-messages/build/amd64-3.9/setup.py", line 68, in <module>
    setup(
  File "/usr/lib/python3.9/vendor-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/vendor-packages/setuptools/_distutils/core.py", line 186, in setup
    return run_commands(dist)
  File "/usr/lib/python3.9/vendor-packages/setuptools/_distutils/core.py", line 202, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.9/vendor-packages/setuptools/_distutils/dist.py", line 983, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/vendor-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/usr/lib/python3.9/vendor-packages/setuptools/_distutils/dist.py", line 1002, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/vendor-packages/setuptools/command/test.py", line 45, in run
    raise RuntimeError("Support for the test command was removed in Setuptools 72")
RuntimeError: Support for the test command was removed in Setuptools 72
py39: exit 1 (0.50 seconds) /data/builds/oi-userland/components/python/teamcity-messages/build/amd64-3.9> python setup.py test pid=252376
  py39: FAIL code 1 (0.53=setup[0.03]+cmd[0.50] seconds)
  evaluation failed :( (0.91 seconds)
```
