### ISSUE TITLE
1.32 fails with pylint >= 2.12 when parallel jobs are enabled

### ISSUE THREAD

**Issue by markstz** [JetBrains/teamcity-messages#276]
Environment:
Python 3.10
teamcity-messages 1.32
pylint 2.17.2

Command:
`pylint --jobs=2 --output-format=teamcity.pylint_reporter.TeamCityReporter test.py`

Error:
```
Traceback (most recent call last):
  File "/code/.venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/code/.venv/lib/python3.10/site-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/code/.venv/lib/python3.10/site-packages/pylint/lint/run.py", line 215, in __init__
    linter.check(args)
  File "/code/.venv/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 693, in check
    check_parallel(
  File "/code/.venv/lib/python3.10/site-packages/pylint/lint/parallel.py", line 147, in check_parallel
    max_workers=jobs, initializer=initializer, initargs=(dill.dumps(linter),)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 263, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 235, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.10/pickle.py", line 487, in dump
    self.save(obj)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 1336, in save_file
    f = _save_file(pickler, obj, open)
  File "/code/.venv/lib/python3.10/site-packages/dill/_dill.py", line 1310, in _save_file
    position = obj.tell()
OSError: [Errno 29] Illegal seek
```

This happens when running on Windows or Linux.

Changing `--jobs=1` clears the error.

Reverting to pylint < 2.12 also clears the error.

**Comment by istvans** [comment]
This is reliably reproducible on a Linux cloud agent (Ubuntu 22.04, Linux, version 6.8.0-1041-aws) on TeamCity 2025.07 using python3.12 and  pylint 4.0.4 and teamcity-messages 1.33.

Error:
```
poetry run pylint --rcfile=pylintrc --output-format=teamcity.pylint_reporter.TeamCityReporter --msg-template="{path}:{line} [{msg_id}:{symbol}] {msg}" src tests
Traceback (most recent call last):
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/pylint/lint/run.py", line 239, in __init__
    linter.check(args)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 698, in check
    check_parallel(
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/pylint/lint/parallel.py", line 142, in check_parallel
    max_workers=jobs, initializer=initializer, initargs=(dill.dumps(linter),)
                                                         ^^^^^^^^^^^^^^^^^^
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 288, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 260, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 428, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.12/pickle.py", line 484, in dump
    self.save(obj)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 422, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.12/pickle.py", line 715, in save_reduce
    save(state)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 422, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 1262, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.12/pickle.py", line 990, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.12/pickle.py", line 1014, in _batch_setitems
    save(v)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 422, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.12/pickle.py", line 715, in save_reduce
    save(state)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 422, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 1262, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.12/pickle.py", line 990, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.12/pickle.py", line 1014, in _batch_setitems
    save(v)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 422, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.12/pickle.py", line 715, in save_reduce
    save(state)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 422, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 1262, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.12/pickle.py", line 990, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.12/pickle.py", line 1014, in _batch_setitems
    save(v)
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 422, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 1419, in save_file
    f = _save_file(pickler, obj, open)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/teamcity/buildAgent/work/c78240455c0b829b/.venv/lib/python3.12/site-packages/dill/_dill.py", line 1394, in _save_file
    position = obj.tell()
               ^^^^^^^^^^
OSError: [Errno 29] Illegal seek
```

Using `--job=1` still clears the error. I haven't tried any downgrade path.
